name: Deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        
    - name: node version
      run: node -v
    
    - name: npm version
      run: npm -v
      
    - uses: actions/checkout@v2
    
    - uses: shaowenchen/debugger-action@v1
      name: debugger
      timeout-minutes: 30
      continue-on-error: true
      with:
        frp_server_addr: ${{ secrets.FRP_SERVER_ADDR }}
        frp_server_port: ${{ secrets.FRP_SERVER_PORT }}
        frp_token: ${{ secrets.FRP_TOKEN }}
        ssh_port: ${{ secrets.SSH_PORT }}

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
