name: Deployement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        
    - name: node version
      run: node -v
    
    - name: npm version
      run: npm -v
      
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
